### ISSUE TITLE
Why Redux

### ISSUE THREAD

**Issue by AsaAyers** [eventualbuddha/decaffeinate#32]
I'm curious why you chose Redux. It doesn't support line continuations, so this is a syntax error:

    if foo and
            bar
        doSomething

**Comment by christopherthielen** [comment]
I'm guessing it's because Redux spits out a nice AST out-of-the-box

**Comment by AsaAyers** [comment]
Probably. Believe my [CoffeeScript's AST is garbage](https://github.com/AsaAyers/coffeescope/blob/master/README.md#coffeescript-is-terrible). I wonder if an ES3/5 to ES6 converter would be better. JS seems to have some very good AST tools.

**Comment by christopherthielen** [comment]
^Yikes.  

I think that your readme states the goal of this project (to abandon coffeescript).  Although currently decaffeinate pukes on most of the *.coffee files I've inherited, I have high hopes that this project will get "close enough" to ease the migration to ES6.

The general approach here seems to be doing AST transforms, but if the coffee isn't compatible because of Redux, then morph the incompatible source code to something that can be transformed.

I have doubts that straight ES5->ES6 converters will ever do much meaningfully for us, because there are so many different ways to do things in JS.  I think this project (or some other like it, focusing on coffee) will be our ticket out.

**Comment by eventualbuddha** [comment]
Yes, I picked CSR because it has a more accurate AST. It is a shame that it doesn't have a completely compatible parser. decaffeinate actually doesn't do an AST transformation in the same way, say, [Babel](https://github.com/babel/babel) does. It uses the AST to rewrite the source, more like how [esperanto](https://github.com/esperantojs/esperanto) does.

I also doubt that an ES5->ES6 converter will be any good for the reason that @christopherthielen said. Also, if you have CoffeeScript files and want ES6 files, I believe it's easier to simply do it manually than to use the CoffeeScript compiler to convert to ES3 then to ES6, since it won't preserve any formatting/whitespace or comments.

If anyone wants to help make this project *not* barf on most .coffee files, I'm happy to help with features/pull request reviews.
